// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk8tofZJsjQXdfkzzQE05PyhN02QMILH0',
    appId: '1:376910963136:web:dcc4e89e4f6ecbadcb6825',
    messagingSenderId: '376910963136',
    projectId: 'shopping-app-c2fe7',
    authDomain: 'shopping-app-c2fe7.firebaseapp.com',
    storageBucket: 'shopping-app-c2fe7.appspot.com',
    measurementId: 'G-0SX22HQHJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoG0YVbN6-Djg5ncXJbWDy8OWzXuYCGWQ',
    appId: '1:376910963136:android:b8f74b2b7d3c530bcb6825',
    messagingSenderId: '376910963136',
    projectId: 'shopping-app-c2fe7',
    storageBucket: 'shopping-app-c2fe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfgJqm53WecW4PKFm2VQKuRUFgxmTWrk',
    appId: '1:376910963136:ios:caad1b4fc6d1f765cb6825',
    messagingSenderId: '376910963136',
    projectId: 'shopping-app-c2fe7',
    storageBucket: 'shopping-app-c2fe7.appspot.com',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABfgJqm53WecW4PKFm2VQKuRUFgxmTWrk',
    appId: '1:376910963136:ios:529d51144b4047a4cb6825',
    messagingSenderId: '376910963136',
    projectId: 'shopping-app-c2fe7',
    storageBucket: 'shopping-app-c2fe7.appspot.com',
    iosBundleId: 'com.example.shopit.RunnerTests',
  );
}
